coffeehouse/coffeehouse/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import MainView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainView.as_view(), name="main"),
    path('coffeehouse/', include('coffeeshop.urls')),
]

coffeehouse/coffeeshop/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView

from .views import EmployeesListView, ScheduleListView, ScheduleCreateView, ScheduleUpdateView, ScheduleDeleteView, LogoutView, ShiftCreateView, weekly_report_view

app_name = "coffeeshop"

urlpatterns = [
    path(
        "login/",
        LoginView.as_view(
            template_name="coffeeshop/login.html",
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("employees/", EmployeesListView.as_view(), name="employees_list"),
    path('employees/<int:pk>/', ScheduleListView.as_view(), name="schedule"),
    path('employees/schedule/create', ScheduleCreateView.as_view(), name="schedule_create"),
    path('employees/<int:pk>/<int:shift_id>/update', ScheduleUpdateView.as_view(), name="schedule_update"),
    path('employees/<int:pk>/<int:shift_id>/delete', ScheduleDeleteView.as_view(), name="schedule_delete"),

    path('employees/<int:pk>/<int:shift_id>/mark/', ShiftCreateView.as_view(), name="mark"),
    path('report/', weekly_report_view, name="report"),
]

coffeehouse/coffeeshop/models.py
from datetime import datetime
from croniter import croniter

from django.db import models
from django.contrib.auth.models import User


class Employee(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Работник')
    fio = models.CharField(max_length=100, null=False, blank=True, verbose_name='ФИО')
    position = models.CharField(max_length=50, null=False, blank=True, verbose_name='Должность')
    weekly_report = models.JSONField(null=True, blank=True, verbose_name='Еженедельный отчет')

    def __str__(self):
        return self.fio or self.position


class Shift(models.Model):
    DAYS = [
        ('monday', 'Понедельник'),
        ('tuesday', 'Вторник'),
        ('wednesday', 'Среда'),
        ('thursday', 'Четверг'),
        ('friday', 'Пятница'),
        ('saturday', 'Суббота'),
        ('sunday', 'Воскресенье'),
    ]
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    day = models.CharField(max_length=12, choices=DAYS)
    start_time = models.TimeField()
    end_time = models.TimeField()


class Attendance(models.Model):
    shift = models.ForeignKey(Shift, on_delete=models.CASCADE, verbose_name="Смена")
    arrival_time = models.DateTimeField(auto_now_add=True, verbose_name="Время прихода")
    departure_time = models.DateTimeField(auto_now=True, verbose_name="Время ухода")


class Report(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, verbose_name="Работник")
    week_start_day = models.DateField(verbose_name="Начальный день")
    week_end_day = models.DateField(verbose_name="Конечный день")
    hours_worked = models.DecimalField(max_digits=5, decimal_places=2, verbose_name="Всего часов отработано")
    rate = models.DecimalField(default=0, max_digits=8, decimal_places=2, verbose_name="Ставка в час")
    late_arrival = models.IntegerField(default=0, verbose_name="Утренние опоздания")
    early_leaving = models.IntegerField(default=0, verbose_name="Вечерний уход раньше смены")
    amount_earned = models.DecimalField(default=0, max_digits=8, decimal_places=2, verbose_name="Итоговая заработанная сумма")

coffeehouse/coffeeshop/forms.py
from datetime import datetime

from django import forms
from .models import Attendance, Shift
from datetime import datetime
from croniter import croniter
from django.forms import ModelForm, ValidationError

# class ShiftCreateForm(forms.ModelForm):
#     class Meta:
#         model = Attendance
#         fields = ['shift']


class ShiftCreateForm(forms.ModelForm):
    class Meta:
        model = Attendance
        fields = ['shift']

    def __init__(self, *args, **kwargs):
        employee_id = kwargs.pop('employee_id')
        shift_id = kwargs.pop('shift_id')
        super().__init__(*args, **kwargs)
        self.fields['shift'] = forms.ModelChoiceField(queryset=Shift.objects.filter(employee_id=employee_id, id=shift_id))

coffeehouse/coffeeshop/views.py
from datetime import datetime

from django.forms import TimeInput, formset_factory
from django import forms
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.contrib.auth.views import LogoutView
from django.views import View
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from .forms import ShiftCreateForm
from .models import Employee, Shift, Attendance, Report


# class ScheduleListView(ListView):
#     template_name = "coffeeshop/employees_schedule_details.html"
#     model = Shift
#     context_object_name = "schedule"


class LogoutView(LogoutView):
    next_page = reverse_lazy('coffeeshop:login')


class EmployeesListView(LoginRequiredMixin, ListView):
    template_name = "coffeeshop/employees_list.html"
    queryset = (
        Employee.objects
        .select_related('user')
    )
    context_object_name = "employees"


class ScheduleListView(ListView):
    template_name = "coffeeshop/employees_schedule_details.html"
    # queryset = (
    #     Shift.objects.select_related('employee')
    # )
    model = Shift
    context_object_name = "schedule"

    def get_queryset(self):
        employee_id = self.kwargs.get('pk')
        employee = get_object_or_404(Employee, id=employee_id)
        self.employee = employee
        return super().get_queryset().filter(employee=employee)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['employee'] = self.employee
        return context


class ScheduleCreateView(UserPassesTestMixin, CreateView):
    def test_func(self):
        return self.request.user.is_superuser

    model = Shift
    fields = "employee", "day", "start_time", "end_time"
    context_object_name = "schedule"
    template_name = "coffeeshop/schedule_form.html"

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['start_time'].widget = TimeInput(format='%H:%M')
        form.fields['end_time'].widget = TimeInput(format='%H:%M')
        return form

    def get_success_url(self):
        employee = self.object.employee
        return reverse('coffeeshop:schedule', kwargs={"pk": employee.pk}, )


class ScheduleUpdateView(UserPassesTestMixin, UpdateView):
    def test_func(self):
        return self.request.user.is_superuser

    model = Shift
    fields = "employee", "day", "start_time", "end_time"
    template_name = 'coffeeshop/schedule_update_form.html'
    context_object_name = "schedule"

    def get_object(self, queryset=None):
        pk = self.kwargs.get('shift_id', None)
        if pk is not None:
            return self.model.objects.get(pk=pk)
        else:
            return super().get_object(queryset)

    def get_success_url(self):
        employee = self.object.employee
        return reverse('coffeeshop:schedule', kwargs={"pk": employee.pk}, )


class ScheduleDeleteView(UserPassesTestMixin, DeleteView):
    def test_func(self):
        return self.request.user.is_superuser

    model = Shift
    template_name = 'coffeeshop/schedule_confirm_delete.html'
    context_object_name = "schedule"

    def get_object(self, queryset=None):
        pk = self.kwargs.get('shift_id', None)
        if pk is not None:
            return self.model.objects.get(pk=pk)
        else:
            return super().get_object(queryset)

    def get_success_url(self):
        employee = self.object.employee
        return reverse('coffeeshop:schedule', kwargs={"pk": employee.pk}, )


class ShiftCreateView(CreateView):

    model = Attendance
    template_name = "coffeeshop/mark_shift.html"
    form_class = ShiftCreateForm

    # def get_queryset(self):
    #     employee_id = self.kwargs.get('pk')
    #     employee = get_object_or_404(Employee, id=employee_id)
    #     self.employee = employee
    #     return super().get_queryset().filter(employee=employee)

    def get_success_url(self):
        # employee = self.object.employee
        # return reverse('coffeeshop:schedule', kwargs={"pk": employee.pk}, )
        return reverse('coffeeshop:employees_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['employee_id'] = self.kwargs['pk']
        kwargs['shift_id'] = self.kwargs.get('shift_id')
        return kwargs

    # def form_valid(self, form):
    #     attendance = form.save(commit=False)
    #     attendance.save()
    #     return super().form_valid(form)

    def form_valid(self, form):
        shift_id = self.kwargs.get('shift_id')

        attendance = Attendance.objects.filter(shift=shift_id).first()

        if attendance:
            attendance.departure_time = datetime.now()
            attendance.save()
        else:
            attendance = form.save(commit=False)
            attendance.save()

        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['employee'] = Employee.objects.get(id=self.kwargs['pk'])
        context['shift'] = Shift.objects.get(id=self.kwargs.get('shift_id'))
        return context

    def get(self, request, *args, **kwargs):
        if 'shift_id' not in self.kwargs:
            return HttpResponseRedirect(reverse('coffeeshop:employees_list'))
        return super().get(request, *args, **kwargs)


def weekly_report_view(request):
    # Получаем список всех сотрудников и их отчетов из базы данных
    employees = Employee.objects.all()

    # Передаем список сотрудников и их отчетов в шаблон для отображения
    return render(request, 'coffeeshop/weekly_report.html', {'employees': employees})

coffeehouse/coffeeshop/templates/coffeeshop/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base Title
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Меню</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="#">Главная</a>
      <a class="nav-item nav-link" href="{% url 'coffeeshop:login' %}" class="btn btn-primary btn-lg">Войти</a>
      <a class="nav-item nav-link" href="{% url 'coffeeshop:logout' %}" class="btn btn-primary btn-lg">Выйти</a>
      <a class="nav-item nav-link" href="{% url 'coffeeshop:employees_list' %}">Работники</a>
    </div>
  </div>
</nav>
    {% block body %}
        Base Body
    {% endblock %}
</body>
</html>

coffeehouse/coffeeshop/templates/coffeeshop/employees_list.html
{% extends 'coffeeshop/base.html' %}

{% block title %}
  Employees
{% endblock %}

{% block body %}
{% if user.is_authenticated %}
<div class="container p-5">
  <h1>Персонал</h1>
  <div class="container p-2">
  {% if employees %}
    {% for employee in employees %}
      <p>Работник: <a href="{% url 'coffeeshop:schedule' pk=employee.pk %}">{{ employee.fio }}</a></p>
      <p>Должность: {{ employee.position }}</p>
    <br>
    {% endfor %}
  {% else %}
    <h2>Еще нет работников</h2>
  {% endif %}
  </div>
</div>
{% else %}
  <h1>Вы еще не авторизовались</h1>
{% endif %}
{% endblock %}

coffeehouse/coffeeshop/templates/coffeeshop/employees_schedule_details.html
{% extends 'coffeeshop/base.html' %}

{% block title %}
  Schedule
{% endblock %}

{% block body %}
<div class="container p-5">
  <h1>Расписание</h1>
{% if user.is_authenticated %}
  <div class="container p-2">
  {% if schedule %}
      <div>
        <p>Работник: {{ employee.fio }}</p>
        <p>Должность: {{ employee.position }}</p>
        {% for shift in schedule %}
          <p>{% if request.user.is_superuser %}<a href="{% url 'coffeeshop:schedule_update' pk=shift.employee.pk shift_id=shift.pk %}">{{ shift.get_day_display }}</a>{% else %}{{ shift.get_day_display }}{% endif %} - {{ shift.start_time|time:"H:i" }}-{{ shift.end_time|time:"H:i" }}
            {% if request.user.is_superuser %}<a href="{% url 'coffeeshop:schedule_delete' pk=shift.employee.pk shift_id=shift.pk %}">Удалить смену</a>{% endif %} <a
                    href="{% url 'coffeeshop:mark' pk=shift.employee.pk shift_id=shift.pk%}">Отметиться</a></p>
        {% endfor %}
      </div>
    <br>
  {% else %}
    <h2>Еще нет смен</h2>
  {% endif %}
{% if request.user.is_superuser %}
  <a href="{% url 'coffeeshop:schedule_create' %}" class="btn btn-success btn-lg">Добавить смену</a>
{% endif %}
{% else %}
  <h2>Пользователь не авторизован</h2>
{% endif %}
<p class="pt-2">
  <a href="{% url 'coffeeshop:employees_list' %}" class="btn btn-primary btn-lg">Вернуться к списку пользователей</a>
</p>
    </div>
</div>
{% endblock %}

coffeehouse/coffeeshop/templates/coffeeshop/login.html
{% extends 'coffeeshop/base.html' %}

{% block title %}
  Login
{% endblock %}

{% block body %}
<div class="p-5">
  <div class="h-100 d-flex justify-content-center align-items-center">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="h-100 d-flex justify-content-center align-items-center">
    <button type="submit" class="btn btn-primary btn-lg">Login</button>
      </div>
  </form>
  </div>
</div>
{% endblock %}

coffeehouse/coffeeshop/templates/coffeeshop/mark_shift.html
{% extends 'coffeeshop/base.html' %}

{% block title %}
  Shift
{% endblock %}

{% block body %}
<div class="container p-5">
  <h1>Смена</h1>
  <div class="container p-2">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary btn-lg">Отметиться</button>
    </form>
  </div>
</div>
{% endblock %}

coffeehouse/coffeeshop/templates/coffeeshop/schedule_confirm_delete.html
{% extends 'coffeeshop/base.html' %}

{% block title %}
  Confirm delete
{% endblock %}

{% block body %}
<div class="container p-5">
  <h1>Вы уверены, что хотите удалить смену на этот день?</h1>
  <br>
  <div>
    <a href="{% url 'coffeeshop:schedule' pk=schedule.employee.pk %}" class="btn btn-success btn-lg">Вернуться к расписанию</a>
  </div>
  <br>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary btn-lg">Удалить</button>
    </form>
  </div>
</div>
{% endblock %}

coffeehouse/coffeeshop/templates/coffeeshop/schedule_form.html
{% extends 'coffeeshop/base.html' %}

{% block title %}
  Create schedule
{% endblock %}

{% block body %}
<div class="container p-5">
    <h1>Создание смены</h1>
  <div class="container">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary btn-lg">Создать</button>
    </form>
  </div>
  <br>
</div>
{% endblock %}

coffeehouse/coffeeshop/templates/coffeeshop/schedule_update_form.html
{% extends 'coffeeshop/base.html' %}

{% block title %}
  Update schedule
{% endblock %}

{% block body %}
<div class="container p-5">
    <h1>Обновление смены</h1>
  <div class="container p-3">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary btn-lg">Обновить</button>
    </form>
    <p class="pt-2">
        <a href="{% url 'coffeeshop:schedule' pk=schedule.employee.pk %}" class="btn btn-success btn-lg">Вернуться к расписанию</a>
    </p>
  </div>
  <br>
</div>
{% endblock %}

coffeehouse/coffeeshop/templates/coffeeshop/weekly_report.html
{% extends 'coffeeshop/base.html' %}

{% block title %}
  Report
{% endblock %}

{% block body %}
  <h1>Отчет о сотрудниках</h1>
    <table>
        <thead>
            <tr>
                <th>Сотрудник</th>
                <th>Отработано часов</th>
                <th>Опоздания (мин)</th>
                <th>Уходы раньше (мин)</th>
                <th>Заработная плата</th>
            </tr>
        </thead>
        <tbody>
            {% for employee in employees %}
            <tr>
                <td>{{ employee.fio }}</td>
                <td>{{ employee.weekly_report.total_hours }}</td>
                <td>{{ employee.weekly_report.total_late_arrivals }}</td>
                <td>{{ employee.weekly_report.total_early_departures }}</td>
                <td>{{ employee.weekly_report.total_earnings }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}