coffeehouse/coffeehouse/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import MainView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainView.as_view(), name="main"),
    path('coffeehouse/', include('coffeeshop.urls')),
]

coffeehouse/coffeeshop/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView

from .views import EmployeesListView, ScheduleListView, ScheduleCreateView, ScheduleUpdateView, ScheduleDeleteView, LogoutView, ShiftCreateView, weekly_report_view

app_name = "coffeeshop"

urlpatterns = [
    path(
        "login/",
        LoginView.as_view(
            template_name="coffeeshop/login.html",
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("employees/", EmployeesListView.as_view(), name="employees_list"),
    path('employees/<int:pk>/', ScheduleListView.as_view(), name="schedule"),
    path('employees/schedule/create', ScheduleCreateView.as_view(), name="schedule_create"),
    path('employees/<int:pk>/<int:shift_id>/update', ScheduleUpdateView.as_view(), name="schedule_update"),
    path('employees/<int:pk>/<int:shift_id>/delete', ScheduleDeleteView.as_view(), name="schedule_delete"),

    path('employees/<int:pk>/<int:shift_id>/mark/', ShiftCreateView.as_view(), name="mark"),
    path('report/', weekly_report_view, name="report"),
]

coffeehouse/coffeehouse/views.py
from django.views.generic import TemplateView


class MainView(TemplateView):
    template_name = 'coffeehouse/main.html'

coffeehouse/coffeehouse/templates/coffeehouse/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
      {% block title %}
        Base Title
      {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Меню</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="#">Главная</a>
      <a class="nav-item nav-link" href="{% url 'coffeeshop:login' %}" class="btn btn-primary btn-lg">Войти</a>
      <a class="nav-item nav-link" href="{% url 'coffeeshop:logout' %}" class="btn btn-primary btn-lg">Выйти</a>
      <a class="nav-item nav-link" href="{% url 'coffeeshop:employees_list' %}">Работники</a>
    </div>
  </div>
</nav>
{% block body%}
  Base Body
{% endblock %}
</body>
</html>

coffeehouse/coffeehouse/templates/coffeehouse/main.html
{% extends 'coffeehouse/base.html' %}

{% block title %}
  Main
{% endblock %}

{% block body %}
    <h1 class="container p-3">Добро пожаловать на главную страницу</h1>
{% endblock %}